// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.bk.example.protobuf.proto;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bk.sample.protobuf.proto.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
