server:
  port: 8080
spring:
  application:
    name: SpringRedisDev

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#        sql: DEBUG
